language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - PATH=$HOME/protobuf/bin:$PATH
before_install:
  - ./install-protobuf.sh
install:
  - pip install codecov
  - pip install -r requirements.txt
  - pushd tests/proto && protoc --python_out=./python *.proto && popd
script:
  - coverage run -m unittest discover .
after_success:
  - codecov
